version: '3'
services:
  db:
    platform: linux/arm64
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    ports:
      - "3307:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Tokyo
      - RAILS_ENV=development
      - EDITOR=vim
    # env_file:
      # - .env
    
volumes:
  mysql_data:
    # 明示的に記載しなくても、デフォルトでローカルストレージを使用する
    # driver: local # Define the driver and options under the volume name
  # web_data: